### PR TITLE
fixed tests written for age_groups()

### PR DESCRIPTION
**Pull request by tinneuro**
The tests in test-tool_functions.R were failing for age_groups(). They are now fixed. For this one of the test data files was renamed because with the new functionality of age_groups() it can deal with data without age column.
The tests for the golem part still fail but are taken care of in another PR.

### CODE REVIEW

**Comment by jaemol** [comment]
Hi! 

The code looks sound and great. 
However, I am unsure of how to test it, as it seems the `app_cache_env` is giving errors, because it is used when running the app, not outside it. 

How have you gotten around that? Just curious, so I can test it fully. :)

**Comment by tinneuro** [comment]
interesting point :) For me when I run Cmd/Ctrl + Shift + T then the tests work and give no error but you are right that of course the app_cache_env is only generated inside the app. How did you try to test it?

**Comment by jaemol** [comment]
Ah, it is my mistake, apologies! 
I have a script locally, which sources all functions in the app and load them - I forgot to source `app_config.R` and create the `app_cache_env`.   

I have now also tested the code and everything runs smoothly. 
Thank you for watching over the wonderfull functions related to `age_groups` :D 

I will approve the review and merge.

**Comment by tinneuro** [comment]
hahaha I will continue to watch them. Thank you for your nice and critical reviews

**Review by jaemol — APPROVED** [review]
I approve these changes.

**Pull request merged**
