### PR TITLE
Feature/add outbreaks to results table

### LINKED ISSUE #286: [FEATURE] add part of a known outbreak to Signal Detection Results Table
**Is your feature request related to a problem? Please describe.**

Several piloting countries want to have the information about how many cases are already identified/part of a known outbreak in the signal detection table. 

**Describe the Solution You'd Like**

Add a column to the signal detection results table at the bottom called "cases in outbreak" which uses the outbreak_status column of the data to compute how many cases have outbreak_status = TRUE of the aggregated cases.

**Describe Alternatives**

**Additional Context**

### PR DESCRIPTION
**Pull request by aj-thl**
Adding column "cases in outbreak" to the signal detection results table.

closes #286

### CODE REVIEW

**Comment by tinneuro** [comment]
Hi @aj-thl ,
thanks so much for tackling this issue! Is it fine for you if I collaborate with you on this PR? I would add some checks/transformations before in case outbreak_status does not have TRUE/FALSE values

**Comment by aj-thl** [comment]
Hi @tinneuro, 

of course, it would be great if you could collaborate with me on this, especially as I have quite limited time available in the coming weeks. Feel free to make any changes :) Thanks for participating!

**Comment by tinneuro** [comment]
Ok great! Maybe you could then still review my changes?

**Comment by aj-thl** [comment]
Sure, let's do so.

**Comment by tinneuro** [comment]
Hi :) I added my changes now and am happy for a review. What I did:
- added outbreak_status to the optional variables so that the data check also checks it so we are sure it is in the correct format for the sum
- add tests for the aggregate_data()
- added outbreak_status to the metadata information and to our example dataset
- enabled level unknown to be shown when filtering (i.e. filtering for outbreak_status that unknown is also shown)

**Comment by aj-thl** [comment]
Hi, 

Great, thank you!

I will try to review the changes that you made at the beginning of next week :) 

Have a nice weekend!

**Review by aj-thl — COMMENTED** [review]
Thank you for your contribution @tinneuro! The changes you have made look good and complement the original formatting a lot. I didn't encounter any bugs related to the outbreak_status variable when I tested the app and I have nothing to add to the changes. Thanks again and great job!

**Comment by tinneuro** [comment]
Great thanks for testing and your review.

**Review by tinneuro — APPROVED** [review]

**Pull request merged**
