### PR TITLE
Adding legend-modification to the plot_regional.R script

### PR DESCRIPTION
**Pull request by AnjaMJ**
Regarding bug #202 

I could not change the legend-shape, but I have removed the confusing second color-line in the plot.
The new plot should just show a single color-line in the legend (see attached)

image

### CODE REVIEW

**Comment by tinneuro** [comment]
Thanks a lot for your contribution! This looks good. Two comments:

- Can you remove the doubled "Cases" below the color scale for the cases. At least for me the legend now has a double Cases title. I can upload a screenshot in case you can not reproduce it
- You do not know this so no problem but can you add a line to NEWS.md under a new header you create on top "SignalDetectionTool 0.3.0" with a short comment that you changed this?

**Comment by tomasmartbert** [comment]
> Thanks a lot for your contribution! This looks good. Two comments:
> 
> * Can you remove the doubled "Cases" below the color scale for the cases. At least for me the legend now has a double Cases title. I can upload a screenshot in case you can not reproduce it

Hi,
I tried to replicate the double-"Cases" bug without luck on the same Linux-server as AnjaMJ. On my Windows laptop, however, I see the bug - but it is also unrelated to the pull request code (I tried uncommenting the changes). 
Comparing the HTML-report interactive vs static it appears the double-"Cases" is introduced in the interactive figure only. The plotly-package version is the same on both machines. 

I have tried with the following package versions:
`ggplot2`:
Windows laptop (R 4.4.0): 3.5.1
Linux (R 4.0.2): 3.4.4

plotly: 4.10.4 

So maybe it is ggplotly issue with a newer ggplot2 version?

> * You do not know this so no problem but can you add a line to NEWS.md under a new header you create on top "SignalDetectionTool 0.3.0" with a short comment that you changed this?

My bad, forgot to tell Anja about the NEWS-file ;-)

**Comment by tinneuro** [comment]
Ok interesting! Thanks for trying out. I have R 4.4.0, ggplot2 3.5.1 and plotly 4.10.4 sp the same as your setting on the windows laptop. Well then I guess we can't really do something about it? Apart from writing to the ggplotly repository...
No worries ;)

**Comment by tinneuro** [comment]
Do you want to finish updating the NEWS file and then we merge? Or do we think it is not so nice with the doubled legend, but yeah we can't currently fix it. Thanks :)

**Comment by AnjaMJ** [comment]
I have updated the NEWS file now 👍 Regarding the doubled legend I think a seperate bug-issue should be created

**Comment by tinneuro** [comment]
Do you mind creating this seperate issue for the legend?

**Review by tinneuro — APPROVED** [review]

**Pull request merged**
